#if defined player_included
	#endinput
#endif

#define player_included

#define enable_register_mode

#include <a_mysql>
#include <PawnPlus>
#include <easyDialog>
#include <samp_bcrypt>
#include <zmessage>

// Legacy
#include <camera_styles>
#include <loading_screen>

#include "ui/player_login_ui.inc"

#include "player_utility.inc"
#include "player_auth.inc"

#include "character/character_stats.inc"

#include "player_spawn_area.inc"

