//------------------------------------------------------//
//														//
//		Author: Tave Nguyen (Vietnam, Can Tho City) 	//
//		Leader Script: 	tavenguyxn						//
//		Supporter: Duy Dang, Bambo						//
//		Scripter: tavenguyxn							//
//		Inspiration: suckless-rp						//
// 														//
//					Copyright (C) 2022 tavenguyen 		//
//======================================================//

#include <a_samp>

/*==============================================================================
	Library Predefinitions
==============================================================================*/

main() {} 
